### ISSUE TITLE
EnvironmentsEnum for DappProvider environment prop

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/dapp-core#104]
A small thing, I wanted to create a PR, but I can't make it work locally with my setup. I have this [warning](https://reactjs.org/warnings/invalid-hook-call-warning.html). Maybe I will try later. 

I wanted to pass the environment as a variable, and I have a problem with typings. I want to use it without the need to cast types. 

![dapp-bug](https://user-images.githubusercontent.com/4427985/154813402-7b4b7868-ccd4-4e66-934a-8c732489c1ed.png)

The problem is with not using `EnvironmentsEnum` in `DappProviderPropsType` for the `environment` prop. I've done quick tests, and it looks like it works ok when switched to the `EnvironmentsEnum` instead of strings.

I have something like that:
```
import { EnvironmentsEnum } from "@elrondnetwork/dapp-core";

export const environment = process.env.NEXT_PUBLIC_ELROND_CHAIN || EnvironmentsEnum.devnet;
```
---
Btw. not related topics:

There is a warning from redux-persist when used with Nextjs, probably something related to running it on the server-side
```
redux-persist failed to create sync storage. falling back to noop storage
```
Also, I saw that there is node-sass used. I think [sass](https://www.npmjs.com/package/sass), the dart version compiled to js, is almost 100% compatible with node-sass and is now recommended. It doesn't require native dependencies, like node-sass, based on libsass.

Btw. here it should be EGLD, right? https://github.com/ElrondNetwork/dapp-core/blob/master/src/constants/network.ts#L45

**Comment by StanislavSava** [comment]
environment should be a string, no need to import it from dapp-core. It's either "devnet", "mainnet" and "testnet"

**Comment by juliancwirko** [comment]
Yes, this is the case when I use:

```
export const environment =
  process.env.NEXT_PUBLIC_ELROND_CHAIN || 'devnet';
```

Then I have the error from the screenshot.
```
Type 'string' is not assignable to type '"devnet" | "testnet" | "mainnet"'
```

Only works when used like that:
```
import { EnvironmentsEnum } from "@elrondnetwork/dapp-core";

export const environment =
  (process.env.NEXT_PUBLIC_ELROND_CHAIN as EnvironmentsEnum) ||
  EnvironmentsEnum.devnet;
```

**Comment by StanislavSava** [comment]
you need to use something like this:

export const environment = process.env.NEXT_PUBLIC_ELROND_CHAIN || "devnet"

Don't use values from that enum, DappProvider accepts only strings

**Comment by juliancwirko** [comment]
It will be simpler to show with the animated gif:
![typings](https://user-images.githubusercontent.com/4427985/155323219-19c0648c-a9a5-490a-8e6e-2ffa5fcb55ac.gif)

**Comment by StanislavSava** [comment]
hey @juliancwirko with the next small update, you'll also be able to pass in a value from EnvironmentsEnum,  so it will be "devnet" | "mainnet" | "testnet" | EnvironmentsEnum.

If you'll still have issues, you can just cast your environment variable to EnvironmentsEnum type

**Comment by StanislavSava** [comment]
yep, we want people to be able to pass in the value as a string, not necessarily as an enum part

**Comment by StanislavSava** [comment]
yep, we want people to be able to pass in the value as a string, not necessarily as an enum part
