### ISSUE TITLE
Issue when connecting through maiar app on mobile phone 

### ISSUE THREAD

**Issue by PaulWCZ** [ElrondNetwork/dapp-core#107]
Hey, I am the last version of dapp-core (1.0.7), I have an issue when I am on my phone and I try to connect with the WalletConnectloginButton, when I click on the Connect button on the dapp it automatically open maiar app, but a white screen appears with the button but we can't click on it, it is permanently charging.

`<WalletConnectLoginButton
              callbackRoute={routeNames.dashboard}
              loginButtonText={'Maiar'}
            />`

![IMG_9568](https://user-images.githubusercontent.com/96685330/155224866-4fed5f5d-2cbf-4629-a626-14ab10ad48a7.PNG)

How to reproduce:
-Install the last version of dapp-core on a dapp
-Take a Phone
-Try to connect with it through the Maiar Button

At the end you can't connect, I believe their is an issue with the 'uriDeepLink'

**Comment by StanislavSava** [comment]
We can't really replicate this, are you passing in a custom network config? Can you try with the latest version, 1.0.8?
