### ISSUE TITLE
DappProvider with Nextjs and ASO

### ISSUE THREAD

**Issue by juliancwirko** [ElrondNetwork/dapp-core#113]
Just observation. When the DappProvider wraps the whole app in Next, it will block [Automatic Static Optimization](https://nextjs.org/docs/advanced-features/automatic-static-optimization). Probably because of the logged-in state checks (additional data requirements), the source code isn't injected. It will be problematic for public pages. 

I think it will be beneficial to add to the docs that with Next, it is not a good idea to wrap the whole app with DappProvider. Probably not every page would need to use dapp-core tools. 

I am not sure yet what more could be done with that. We probably can't wrap small components on the page and use, for example, more than one DappProvider, it will probably work, but the whole logic will be multiplied. But usage on chosen pages that require auth and dapp-core tools should be enough.

**Comment by StanislavSava** [comment]
Could you please provide us with a PR with this improvement?

**Comment by juliancwirko** [comment]
My idea would be not to use the wrapper (DappProvider) but some logic to synchronize providers and accounts on app load. So, reading from local storage, setting up providers, synchronizing user accounts, etc. So I'm afraid that it would be a bigger change.

It could be, for example, React hook, plus rerendering optimization. Then the developer could decide which content requires data checks for auth state and could be able to determine which parts will wait for the state to resolve (checking 'pending' state).

This way, only small parts of the code will be affected by blocking state checks, and also, the devs could gain more control over that.

I work on a custom implementation of such logic, so I can share it here when ready. I plan to have something usable at the beginning of April.

**Comment by StanislavSava** [comment]
Alright, until then, I will close this issue and wait for the PR
