### ISSUE TITLE
interpretQueryResponse missed one BigUint value - zero value

### ISSUE THREAD

**Issue by icegriffinguru** [ElrondNetwork/dapp-core#122]
I made a view function return a tuple of 3 BigUints and 2 u32s. (all of them were zeroes.)
```
#[view(getAccountState)]
    fn get_account_state(&self, caller: ManagedAddress) -> (BigUint, BigUint, BigUint, u32, u32)
```
ABI clearly shows the return type.
```
{
            "name": "getAccountState",
            "mutability": "readonly",
            "inputs": [
                {
                    "name": "caller",
                    "type": "Address"
                }
            ],
            "outputs": [
                {
                    "type": "tuple<BigUint,BigUint,BigUint,u32,u32>"
                }
            ]
        }
```
but i got 2 BigUints and 2 u32s after using interpretQueryResponse.

![image](https://user-images.githubusercontent.com/97042732/156642476-67f9c281-b7bb-4404-be01-3b232184bded.png)

**Comment by StanislavSava** [comment]
This doesn't seem related to dapp-core, please open an issue on the relevant library
