### ISSUE TITLE
Hooks for tracking transaction statuses not exposed in dapp-core?

### ISSUE THREAD

**Issue by andreiantonescu** [ElrondNetwork/dapp-core#142]
Not sure if the readme is not updated but some of the hooks under the header "Tracking transactions' statuses" do not seem to be exposed in the lastest version of dapp-core:

- useGetSuccessfulTransactions
- useGetFailedTransactions
- useGetCompletedTransactions
- useGetActiveTransactionsStatus

**Comment by StanislavSava** [comment]
These hooks are exposed via the transactionServices object that is exported from dapp-core

import {  transactionServices } from "@elrondnetwork/dapp-core";
