### ISSUE TITLE
Unable to use useGetCompletedTransactions hook.

### ISSUE THREAD

**Issue by CristianFodor** [ElrondNetwork/dapp-core#196]
When I try to use this hook inside my project an error is trow and it let's me know that the hook can't be found in dapp-core.

`Module not found: Can't resolve '@elrondnetwork/dapp-core/dist/services' in ...`

I'm using the last version of dapp-core. v1.1.10

**Comment by StanislavSava** [comment]
please do a rm -rf node_modules && npm i, this could be a cache problem

**Comment by StanislavSava** [comment]
I will close this issue due to lack of activity
