### ISSUE TITLE
Signing transactions using Web Wallet through Maiar returns 'rejected by user'

### ISSUE THREAD

**Issue by damienen** [ElrondNetwork/dapp-core#200]
dapp-core version: 1.1.11
erdjs version: 10.1.2

It seems that if I login to Web Wallet using Maiar I cannot sign transactions as it returns an 'rejected by user' error on the Web Wallet interface. I have tried using Web Wallet and Keystore and it works. This has only been tested in devnet-wallet

Transaction example:

  const sendMintTransaction = async (quantity: number) => {
    const val = quantity * price;
    const swapTransaction = {
      value: val,
      data: 'mintRandomNft',
      receiver: contractAddress,
      gasLimit: Math.round(2000000 + (quantity / price) * 1500000)
    };
    await refreshAccount();
    const { sessionId, error } = await sendTransactions({
      transactions: swapTransaction,
      transactionsDisplayInfo: {
        processingMessage: 'NFT minting in progress',
        errorMessage: 'Error occured during NFT minting',
        successMessage: 'NFT minting successful'
      },
      redirectAfterSign: false
    });
    if (sessionId != null) {
      setTransactionSessionId(sessionId);
    }
  };

**Comment by StanislavSava** [comment]
This doesn't seem to be an issue with dapp-core, but with web-wallet

**Comment by newbreedofgeek** [comment]
@StanislavSava where do we raise issues with Web Wallet then? This is a blocker for our DApp
