### ISSUE TITLE
All transactions seems as successful in TransactionToasts

### ISSUE THREAD

**Issue by damienen** [ElrondNetwork/dapp-core#201]
dapp-core version: 1.1.11
erdjs version: 10.1.2

Whenever I send a transaction it shows as a successful one in the Transaction Toasts, even though it has failed. This has been tested in both devnet and mainnet. This is the code snippet for sending the transaction: 

  const sendMintTransaction = async (quantity: number) => {
    const val = quantity * Math.pow(10, 18);
    const swapTransaction = {
      value: val,
      data: 'mintRandomNft',
      receiver: contractAddress,
      gasLimit: Math.round(2000000 + (quantity / price) * 1500000)
    };
    await refreshAccount();
    const { sessionId, error } = await sendTransactions({
      transactions: swapTransaction,
      transactionsDisplayInfo: {
        processingMessage: 'NFT minting in progress',
        errorMessage: 'Error occured during NFT minting',
        successMessage: 'NFT minting successful'
      },
      redirectAfterSign: false
    });
    if (sessionId != null) {
      setTransactionSessionId(sessionId);
    }
  };

**Comment by Mandy9943** [comment]
the thing happend to me, this is the error I got in console 

index.js:1 TypeError: Cannot read properties of undefined (reading 'find')
    at _loop (TransactionStatusTracker.tsx:135)
    at TransactionStatusTracker.tsx:93
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:3973
_loop @ TransactionStatusTracker.tsx:166
(anonymous) @ TransactionStatusTracker.tsx:93
Promise.then (async)
(anonymous) @ TransactionStatusTracker.tsx:54
_catch @ helpers.mjs:565
checkTransactionStatus @ TransactionStatusTracker.tsx:54
(anonymous) @ TransactionStatusTracker.tsx:178
setInterval (async)
(anonymous) @ TransactionStatusTracker.tsx:177
commitHookEffectListMount @ react-dom.development.js:22969
commitPassiveMountOnFiber @ react-dom.development.js:24702
commitPassiveMountEffects_complete @ react-dom.development.js:24666
commitPassiveMountEffects_begin @ react-dom.development.js:24653
commitPassiveMountEffects @ react-dom.development.js:24641
flushPassiveEffectsImpl @ react-dom.development.js:26848
flushPassiveEffects @ react-dom.development.js:26801
(anonymous) @ react-dom.development.js:26597
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
performWorkUntilDeadline @ scheduler.development.js:538
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27329
ensureRootIsScheduled @ react-dom.development.js:25522
scheduleUpdateOnFiber @ react-dom.development.js:25316
dispatchReducerAction @ react-dom.development.js:17269
checkForUpdates @ useSelector.js:78
handleChangeWrapper @ Subscription.js:90
(anonymous) @ Subscription.js:19
batchedUpdates$1 @ react-dom.development.js:25979
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
handleChangeWrapper @ Subscription.js:90
dispatch @ redux.js:297
e @ VM23:2494
(anonymous) @ loginSessionMiddleware.ts:51
(anonymous) @ serializableStateInvariantMiddleware.ts:197
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:258
dispatch @ VM23:3665
(anonymous) @ index.ts:84
Promise.then (async)
(anonymous) @ index.ts:42
_catch @ helpers.mjs:565
(anonymous) @ index.ts:37
_finallyRethrows @ helpers.mjs:578
(anonymous) @ index.ts:37
_cycle @ helpers.mjs:175
_forOf @ helpers.mjs:194
handleSendTransactions @ index.ts:37
(anonymous) @ index.ts:112
commitHookEffectListMount @ react-dom.development.js:22969
commitPassiveMountOnFiber @ react-dom.development.js:24702
commitPassiveMountEffects_complete @ react-dom.development.js:24666
commitPassiveMountEffects_begin @ react-dom.development.js:24653
commitPassiveMountEffects @ react-dom.development.js:24641
flushPassiveEffectsImpl @ react-dom.development.js:26848
flushPassiveEffects @ react-dom.development.js:26801
(anonymous) @ react-dom.development.js:26597
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
performWorkUntilDeadline @ scheduler.development.js:538
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
performWorkUntilDeadline @ scheduler.development.js:538
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27329
ensureRootIsScheduled @ react-dom.development.js:25522
scheduleUpdateOnFiber @ react-dom.development.js:25316
dispatchReducerAction @ react-dom.development.js:17269
checkForUpdates @ useSelector.js:78
handleChangeWrapper @ Subscription.js:90
(anonymous) @ Subscription.js:19
batchedUpdates$1 @ react-dom.development.js:25979
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
handleChangeWrapper @ Subscription.js:90
dispatch @ redux.js:297
e @ VM23:2494
(anonymous) @ loginSessionMiddleware.ts:51
(anonymous) @ serializableStateInvariantMiddleware.ts:167
(anonymous) @ index.js:20
(anonymous) @ immutableStateInvariantMiddleware.ts:258
dispatch @ VM23:3665
(anonymous) @ ProviderInitializer.tsx:87
Promise.then (async)
(anonymous) @ ProviderInitializer.tsx:85
_catch @ helpers.mjs:565
(anonymous) @ ProviderInitializer.tsx:85
fetchAccount @ ProviderInitializer.tsx:106
(anonymous) @ ProviderInitializer.tsx:68
commitHookEffectListMount @ react-dom.development.js:22969
commitPassiveMountOnFiber @ react-dom.development.js:24702
commitPassiveMountEffects_complete @ react-dom.development.js:24666
commitPassiveMountEffects_begin @ react-dom.development.js:24653
commitPassiveMountEffects @ react-dom.development.js:24641
flushPassiveEffectsImpl @ react-dom.development.js:26848
flushPassiveEffects @ react-dom.development.js:26801
(anonymous) @ react-dom.development.js:26597
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27329
ensureRootIsScheduled @ react-dom.development.js:25522
scheduleUpdateOnFiber @ react-dom.development.js:25316
dispatchSetState @ react-dom.development.js:17342
(anonymous) @ AppInitializer.tsx:68
Promise.then (async)
initializeApp @ AppInitializer.tsx:67
(anonymous) @ AppInitializer.tsx:84
commitHookEffectListMount @ react-dom.development.js:22969
commitPassiveMountOnFiber @ react-dom.development.js:24702
commitPassiveMountEffects_complete @ react-dom.development.js:24666
commitPassiveMountEffects_begin @ react-dom.development.js:24653
commitPassiveMountEffects @ react-dom.development.js:24641
flushPassiveEffectsImpl @ react-dom.development.js:26848
flushPassiveEffects @ react-dom.development.js:26801
commitRootImpl @ react-dom.development.js:26752
commitRoot @ react-dom.development.js:26517
performSyncWorkOnRoot @ react-dom.development.js:25956
flushSyncCallbacks @ react-dom.development.js:11982
commitRootImpl @ react-dom.development.js:26776
commitRoot @ react-dom.development.js:26517
finishConcurrentRender @ react-dom.development.js:25820
performConcurrentWorkOnRoot @ react-dom.development.js:25648
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27329
commitRootImpl @ react-dom.development.js:26596
commitRoot @ react-dom.development.js:26517
performSyncWorkOnRoot @ react-dom.development.js:25956
flushSyncCallbacks @ react-dom.development.js:11982
flushSync @ react-dom.development.js:26040
legacyCreateRootFromDOMContainer @ react-dom.development.js:29309
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29335
render @ react-dom.development.js:29419
Toaster @ chakra-ui-toast.esm.js:504
./node_modules/@chakra-ui/toast/dist/chakra-ui-toast.esm.js @ chakra-ui-toast.esm.js:509
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
./node_modules/@chakra-ui/react/dist/chakra-ui-react.esm.js @ chakra-ui-react.esm.js:1
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ routes.js:115
./src/views/Authentication/SignIn/ConnectView.js @ ConnectView.js:57
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ store.js:12
./src/routes.js @ routes.js:115
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
(anonymous) @ index.css?bb0a:82
./src/index.js @ index.js:26
__webpack_require__ @ bootstrap:856
fn @ bootstrap:150
1 @ ConnectView.js:57
__webpack_require__ @ bootstrap:856
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.chunk.js:1
Show 38 more frames

**Comment by StanislavSava** [comment]
Could you please look a bit close and maybe track this issue in the code? Also, I noticed you're using erdjs 10, dapp-core has not yet transitioned to erdjs 10, that could be the issue

**Comment by StanislavSava** [comment]
This should be fixed in 1.1.20
