### ISSUE TITLE
DappUI.ExtensionLoginButton children doesn't work if no browser extension installed

### ISSUE THREAD

**Issue by weetrax** [ElrondNetwork/dapp-core#203]
Hello Elrond Team !

I don't know if it's an issue or not, but when I set a children to my DappUI.ExtensionLoginButton component, it doesn't work.
**Children only appear** if I have the Maiar Extension installed to my browser.

It's a bit annoying because the UI doesn't fit with my others login components.

version: @elrondnetwork/dapp-core: "1.0.13"

Code sample: 

```js
<DappUI.ExtensionLoginButton callbackRoute={loginRoute} buttonClassName="unlock-extension-login">
  <div className="text-left d-flex align-items-center justify-content-between gap-2">
    <div className="d-flex align-items-center">
      <div className="unlock-icon">
        <SVGMaiarDefiWallet />
      </div>
      <span>Maiar DeFi Extension Wallet</span>
    </div>
    <div>
      <FontAwesomeIcon icon={faChevronRight} size="1x" />
    </div>
  </div>
</DappUI.ExtensionLoginButton>
```

screen **with** extension installed:
![image](https://user-images.githubusercontent.com/17180151/165952035-90716a13-7055-420b-b774-d8935cda1256.png)

screen **without** extension installed:
![image](https://user-images.githubusercontent.com/17180151/165951607-245ef76e-0dd6-4ea6-9af0-c83ea25439ba.png)

**Comment by StanislavSava** [comment]
You can easily customize the UI via custom classNames. If you look at the source code, you'll see that the children do get rendered, but under different html. Maybe you have a special case that needs special handling. Please see if you need some extra attributes and open a PR

**Comment by StanislavSava** [comment]
I will close this issue due to lack of activity
