### ISSUE TITLE
UI issue for modals

### ISSUE THREAD

**Issue by Not-Wadu** [ElrondNetwork/dapp-core#222]
Hello, I have. a issue with the UI, seems like the modal from login is not a modal, I have done like these:
- importe -> import '@elrondnetwork/dapp-core/build/index.css'; is not in the package so I have to import something like this @import '@elrondnetwork/dapp-core/dist/index.css';
-the buttons are ok but the modal is on the bottom of the screen...not a modal

**Comment by Not-Wadu** [comment]
And another thing...with mamar login what must be configured to redirect our page (I work on localhost for now )?

**Comment by Not-Wadu** [comment]
And another question, how I can buy Elrond coins using dopp-core library?

**Comment by Not-Wadu** [comment]
can I use these library to create nfts?

**Comment by StanislavSava** [comment]
Do you have this issue with 2.0 alpha too?

**Comment by Not-Wadu** [comment]
yes, the same problem

**Comment by cipriandraghici93** [comment]
@Not-Wadu please use 2.0.0-alpha.18. You don't have to import any css

**Comment by CiprianDraghici** [comment]
Each UI component has a property called `className` which allows you to set an anchor class on the UI component wrapper. Using this class you can customize/override the base component style. If the property is not passed, a default anchor class is added automatically at the end of the classes attached on the component wrapper. The default `className` added has `dapp-` prefix. 

Eg. For `TransactionToast` component the default `className` is `dapp-transaction-toast`
<img width="823" alt="Screenshot 2022-07-30 at 15 01 56" src="https://user-images.githubusercontent.com/11082863/181910703-06286a06-5cdc-4bac-8828-484bd9b3e626.png">

**Comment by CiprianDraghici** [comment]
Closing this because all the information to fix the issue were provided.
