### ISSUE TITLE
no data in transactions

### ISSUE THREAD

**Issue by Mandy9943** [ElrondNetwork/dapp-core#224]
Hello, I have a problem... I am migrating from dapp-core 1.0.0 to 1.1.21 and in the last version I do not get any data (I pass a payload and it is as if nothing has happened to it) but in version 1.0.0 it works perfectly.
I think I will explain my self in this images

No data (this happends in maiar wallet too  and the others providers)
![image](https://user-images.githubusercontent.com/74042888/169140610-0b1ace27-6859-457f-a21c-3f5f48583171.png)

my code
![image](https://user-images.githubusercontent.com/74042888/169140850-7d4dd381-6232-4f34-b928-b91b4ee6e248.png)
![image](https://user-images.githubusercontent.com/74042888/169140922-bb2b7cdd-a9ca-414e-b01d-c6ec798b7aff.png)

the tx object from the code
![image](https://user-images.githubusercontent.com/74042888/169140978-9f6aace6-9811-46fd-ba3f-ed14387e2195.png)

**Comment by StanislavSava** [comment]
the data has to be a string to a simple transaction to go through. You could build the transaction in a complex object, which will be forwarded directly to the provider. Please see "Transaction" object from erdjs. const tx = new Transaction(transaction)

**Comment by Mandy9943** [comment]
problem solve thanks StanislavSava
