### ISSUE TITLE
Transaction timeout

### ISSUE THREAD

**Issue by adrianslr** [ElrondNetwork/dapp-core#244]
Hello,

I'm trying to set the timeout for a transaction but i cant find out how.

I'm using the following code:

```
const { sessionId } = await sendTransactions({
    transactions: tx
  });
  
  if(sessionId != null) {
    setTransactionSessionId(sessionId);
  }
```

I hope i dont have an older version of the dapp but i cant update right now and this timeout settings needs to be changed asap in my code.

Does anyone have any idea?

**Comment by StanislavSava** [comment]
I'll close this issue do lack of activity
