### ISSUE TITLE
Redirected to web wallet after WalletConnectLoginButton click

### ISSUE THREAD

**Issue by bastw055** [ElrondNetwork/dapp-core#401]
Hey,

I've an issue with the component `WalletConnectLoginButton`, if I click on the button I am redirected to the web wallet. normally a modal should open (according to the docs). 

here is my component

```jsx
import React, { useState } from "react";
import Box from "@mui/material/Box";
import Grid from "@mui/material/Grid";
import Modal from "@mui/material/Modal";
import Button from "@mui/material/Button";
import {
  useGetLoginInfo,
  useGetAccountProvider,
} from "@elrondnetwork/dapp-core/hooks";
import { logout } from "@elrondnetwork/dapp-core/utils/logout";
import { DappProvider } from "@elrondnetwork/dapp-core/wrappers";
import {
  TransactionsToastList,
  SignTransactionsModals,
  NotificationModal,
  SignWithDeviceModal,
  SignWithExtensionModal,
  SignWithLedgerModal,
  WalletConnectLoginButton
} from '@elrondnetwork/dapp-core/UI';
import { SignableMessage } from '@elrondnetwork/erdjs';


export default function ElrondTransactionModal(props) {
  const loginInfo = useGetLoginInfo();
  const environment = "devnet";

  console.log(loginInfo)

  const renderContent = () => {
    if (loginInfo.isLoggedIn === false) {
      return (<WalletConnectLoginButton
              loginButtonText={'Maiar'}
            />);
    } else {
      return <div>logged</div>;
    }
  };

  return (
    <DappProvider
      environment={environment}
    >
      <NotificationModal />
      <TransactionsToastList />
      <SignTransactionsModals />
      <TransactionsToastList />
      <SignWithDeviceModal />
      <SignWithExtensionModal visible={true} />
      <SignWithLedgerModal />    
      <div>
        <Modal open={true} onClose={props.closeHandler} disableAutoFocus={true}>
          <Box>
            <Grid container spacing={2}>
              <Grid item xs={12}>
                {renderContent()}
              </Grid>
            </Grid>
          </Box>
        </Modal>
      </div>
    </DappProvider>
  );
}
```

I'm using these versions, I've tried with `dapp-core 2.0.0-alpha-10` (the version used in dapp-template), same result

    "@elrondnetwork/dapp-core": "2.0.1",
    "@elrondnetwork/erdjs": "11.0.0",
    "@elrondnetwork/erdjs-network-providers": "1.1.0",
    "@elrondnetwork/erdjs-wallet-connect-provider": "2.0.3",

I've tried with `WalletConnectLoginContainer  `directly without `WalletConnectLoginButton`, same issue, I guess the redirection is triggered somewhere in WalletConnectLoginContainer  .

Did I miss something a config or something else?

**Comment by arhtudormorar** [comment]
Hi! Can you also include the imports used in this file? (what comes above your code)

**Comment by bastw055** [comment]
> Hi! Can you also include the imports used in this file? (what comes above your code)

👍 code updated

**Comment by bastw055** [comment]
Any comment / solution?

**Comment by bastw055** [comment]
For the next ones that will have the same problem, you have to remove "React.StrictMode" from your index.js (idk why, I'm not an expert with React)

It would be nice to specify this in the doc @arhtudormorar
