### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by expeluo** [ElrondNetwork/dapp-core#407]
In the readme appears this:
Account
import {
  useGetAccountInfo,
  useGetAccountProvider,
  useGetLoginInfo
 } from '@elrondnetwork/dapp-core/hooks/accounts';

but accounts folder doesn't exist. it must be account

**Comment by tannerhallman** [comment]
You are correct - the import needs to be `account`
https://github.com/ElrondNetwork/dapp-core#account

**Comment by tannerhallman** [comment]
Made a PR: https://github.com/ElrondNetwork/dapp-core/pull/410

**Comment by arhtudormorar** [comment]
PR merged
