### ISSUE TITLE
Next.js -> Getting the auth info in server side code

### ISSUE THREAD

**Issue by Alannek1992** [ElrondNetwork/dapp-core#44]
Hi Guys,

Thanks for your effort and splitting the library. I started using dapp-core yesterday together with next.js and I am able to log in via maiar quite easily. 

Is there a way how to get the auth information about the user in server-side code? Check the snippet below.

```
import { getIsLoggedIn } from "@elrondnetwork/dapp-core";
import { GetServerSideProps, NextPage } from "next";

const MyCollectionPage: NextPage = () => {
  return <div>Just For Test</div>;
};

export default MyCollectionPage;

export const getServerSideProps: GetServerSideProps = async () => {
  const isLoggedIn = getIsLoggedIn();
  console.log(isLoggedIn);
  if (!isLoggedIn) {
    return {
      redirect: {
        destination: "/auth/connect",
        permanent: false,
      },
    };
  }
  return { props: {} };
};
```

Function getIsLoggedIn does not fail, but it always returns a false even though I am logged in. Thanks for your answers.

**Comment by theodornitu** [comment]
Hi there, not quite related to your question but: How did you manage to import dapp-core into next js? I got a lot of dependencies errors.

**Comment by Alannek1992** [comment]
Could you be more concrete? Have you tried that after the latest changes to dapp-core library?

**Comment by theodornitu** [comment]
I tried it with dapp initially, then dapp-core and it worked ok. I had to update config.next.js as well to solve the "fs" issue. :)

**Comment by Alannek1992** [comment]
Perfect, glad that it works 🙂

**Comment by StanislavSava** [comment]
@Alannek1992 since that function is reading from redux, I don't think you can directly call it on server-side and get the current value, it's just returning the default value. I think you'll have to either implement the redirect logic on the front-end or create a mechanism of communicating with the browser.

as per getServerSideProps docs "getServerSideProps only runs on server-side and never runs on the browser" so it has no means to access to browser's state, i.e. fresh redux data.

**Comment by Alannek1992** [comment]
Yea, the simplest solution seems to be to use cookies as a part of the request. Then in getServerSideProps I can extract the information. Anyway, thank you for your response.

**Comment by StanislavSava** [comment]
I'll close this issue for housekeeping. If you have any questions or encounter any bugs, please let us know. Happy hacking.

**Comment by adshodgson** [comment]
For those struggling with the Fs error whilst compiling in NextJS projects,
Add the below to your next.config.js file (webpack5) it will surpress the error.

`module.exports = {
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.resolve.fallback.fs = false;
    }
    return config;
  },`
  
  Thanks Elrond team for creating this intuitive Dapp Solution
