### ISSUE TITLE
Types have separate declarations of a private property 'nonce'.

### ISSUE THREAD

**Issue by Sirfrancis18** [ElrondNetwork/dapp-core#447]
Argument of type 'import("App/node_modules/@elrondnetwork/erdjs/out/transaction").Transaction' is not assignable to parameter of type 'import("App/node_modules/@elrondnetwork/dapp-core/node_modules/@elrondnetwork/erdjs/out/transaction").Transaction'.
  **Types have separate declarations of a private property 'nonce'.  TS2345**
```
import { Transaction, TransactionPayload, Address } from '@elrondnetwork/erdjs';
import { contractAddress } from 'config';
...
  const { address, account } = useGetAccountInfo();
  const { provider } = useGetAccountProvider();
  const { network } = useGetNetworkConfig();
...

const innerTx = new Transaction({
          nonce: account.nonce,
          sender: new Address(address),
          receiver: new Address(contractAddress),
          gasLimit: 0,
          chainID: network.chainId,
          data: new TransactionPayload('play'),
        });
 provider.signTransaction(innerTx)
.then((signedTx) => {
    console.log(signedTx)}
```
this error not happen in dap 2.0, but yes in 2.1.0
Any clue?

**Comment by CiprianDraghici** [comment]
@Sirfrancis18 could you update your comment with the package.json file ?

**Comment by Sirfrancis18** [comment]
the same this dapp

**Comment by CiprianDraghici** [comment]
I am not sure that I understood correctly the provided solution. I will close the issue until further info as you are not blocked anymore. If anyone has a similar issue, please open a new issue.
