### ISSUE TITLE
Signing transactions doesn't work with Elrond web wallet

### ISSUE THREAD

**Issue by ethwork** [ElrondNetwork/dapp-core#59]
I am trying to sign transactions with Elrond web wallet since signing messages is not supported. The following just redirects the user to the web wallet dashboard and does nothing:

```javascript
const SignMessageBtn = () => {
  const { provider } = useGetAccountProvider();
  const { address } = useGetAccountInfo();

  const handleClick = async () => {
    const tx = new Transaction({
          receiver: new Address(address),
          data: new TransactionPayload("my payload")
        });

    const signedTx = await provider.signTransaction(tx);
  };

  return  <button onClick={handleClick}>sign</button>
};
```

If I use `sendTransaction` instead of `signTransaction`, it works as intended (a popup opens asking you to confirm etc)

**Comment by StanislavSava** [comment]
@ethwork it looks like the walletProvider's `signTransaction` method misbehaves here. Also, the payload is incomplete. Try to use the `signTransactions` method and you need to also specify the chainID and the gasLimit.

```
 const handleClick = async () => {
    const tx = new Transaction({
      receiver: new Address(address),
      data: new TransactionPayload('my payload'),
      chainID: new ChainID('T'),
      gasLimit: new GasLimit(100_000)
    });
    const signedTx = await provider.signTransaction( [ tx ] );
    ```

**Comment by StanislavSava** [comment]
I will close this issue due to lack of activity. Please let us know if you encounter other problems.
