### ISSUE TITLE
Disconnecting from Maiar App does not redirect to logout route

### ISSUE THREAD

**Issue by joaquin-alfaro** [ElrondNetwork/dapp-core#88]
When disconnecting from _Maiar App_ **dapp-core** does not redirect to the logout route.

### Expected behavior
When disconnecting from _Maiar App_ I was expecting that the dapp was redirected to the url specified by the property _logoutRoute_ of the component **WalletConnectLoginContainer**

### Actual behavior
The dapp is redirected to the url specified by the property _callbackRoute_ of the component **WalletConnectLoginContainer**

### Steps to reproduce the behavior
1. Use the component **WalletConnectLoginContainer** in a dapp to connect using Maiar App. Specify the value '/logged' for _callbackRoute_ and '/notlogged' for _logoutRoute_
```
<DappUI.WalletConnectLoginContainer
    callbackRoute='/logged'
    loginButtonText={loginButtonText}
    redirectAfterLogin={redirectAfterLogin}
    logoutRoute='/notlogged'
    onClose={handleCloseModal}
/>
```
2. Connect using _Maiar App_. The dapp is redirected to '/logged' as expected.
3. Disconnect using _Maiar App_. The dapp is redirected to '/logged' as it was expected to be redirected to '/notlogged'

### Cause of the issue
The function **handleOnLogout** defined in **useWalletConnectLogin.ts** is redirecting to _callbackRoute_ instead of _logoutRoute_.
```
  const handleOnLogout = () => {
    logout(callbackRoute);
  };
```

I don't know if there is a reason for this behaviour or if it can be changed. 

Thanks for your help

**Comment by StanislavSava** [comment]
Fixed in 1.0.7
